### ISSUE TITLE
Make the BOT embed the image instead of posting a link to it

### ISSUE THREAD

**Issue by netux** [lana2514/lana-bot#1]
In other words, make it do this
![no link](https://user-images.githubusercontent.com/6181929/72377145-f859b880-36ed-11ea-8aea-bdbf982a6ede.png)
instead of this
![link](https://user-images.githubusercontent.com/6181929/72377158-00195d00-36ee-11ea-966a-058f2d644a5b.png)

So it looks more professional.

**Comment by FunnyInternet** [comment]
done
